from .array import ParamArray
from .slicer import SlicerParamArray
from .com import ComParamArray
from .phaser import PhaserParamArray
from .flanger import FlangerParamArray
from .comp import CompParamArray
from .noise_suppressor import NSParamArray
from .overtone import OvertoneParamArray
from .peq import ParaEQParamArray
from .tremolo import TremoloParamArray
from .mixer import MixerParamArray
from .beat import BeatParamArray
from .divider import DividerParamArray
